"""Add imported flag for room sizes

Revision ID: 3049ba88e64a
Revises: 3c63cadb1993
Create Date: 2015-02-24 09:28:28.852000

"""

# revision identifiers, used by Alembic.
revision = '3049ba88e64a'
down_revision = '3c63cadb1993'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_live():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('size_imported', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade_live():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'size_imported')
    ### end Alembic commands ###

