"""Add index

Revision ID: 36987f374a3d
Revises: c50465c5e783
Create Date: 2016-02-15 22:12:15.811000

"""

# revision identifiers, used by Alembic.
revision = '36987f374a3d'
down_revision = 'c50465c5e783'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_live():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_occupancies_resident_id'), 'occupancies', ['resident_id'], unique=False)
    ### end Alembic commands ###


def downgrade_live():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occupancies_resident_id'), table_name='occupancies')
    ### end Alembic commands ###

