"""add set and ensuite columns

Revision ID: 3c63cadb1993
Revises: 6855b5d0c8b
Create Date: 2015-02-18 22:45:26.313000

"""

# revision identifiers, used by Alembic.
revision = '3c63cadb1993'
down_revision = '6855b5d0c8b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_live():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_ensuite', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('is_set', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade_live():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_set')
    op.drop_column('rooms', 'is_ensuite')
    ### end Alembic commands ###

