"""add placesummary

Revision ID: 6f5ad3049b5c
Revises: 06dff4fbb0d4
Create Date: 2016-02-09 22:07:51.367000

"""

# revision identifiers, used by Alembic.
revision = '6f5ad3049b5c'
down_revision = '06dff4fbb0d4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_live():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_summaries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('published_at', sa.DateTime(), nullable=False),
        sa.Column('place_id', sa.Integer(), nullable=False),
        sa.Column('editor_id', sa.String(length=10), nullable=True),
        sa.Column('hidden', sa.Boolean(), nullable=False),
        sa.Column('markdown_content', sa.UnicodeText(), nullable=False),
        sa.ForeignKeyConstraint(['editor_id'], [u'people.crsid'], ),
        sa.ForeignKeyConstraint(['place_id'], [u'places.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_summaries_place_id'), 'place_summaries', ['place_id'], unique=False)
    ### end Alembic commands ###


def downgrade_live():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_summaries_place_id'), table_name='place_summaries')
    op.drop_table('place_summaries')
    ### end Alembic commands ###

