"""add room bands

Revision ID: ed2884b09601
Revises: 6f5ad3049b5c
Create Date: 2016-02-14 15:10:04.944000

"""

# revision identifiers, used by Alembic.
revision = 'ed2884b09601'
down_revision = '6f5ad3049b5c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_live():
    ### commands auto generated by Alembic - please adjust! ###
    bands = op.create_table('room_bands',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Unicode(length=255), nullable=True),
        sa.Column('description', sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    modifiers = op.create_table('room_band_modifiers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Unicode(length=255), nullable=True),
        sa.Column('description', sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    modifier_prices = op.create_table('room_band_modifier_prices',
        sa.Column('modifier_id', sa.Integer(), nullable=False),
        sa.Column('season_id', sa.Integer(), nullable=False),
        sa.Column('discount', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.ForeignKeyConstraint(['modifier_id'], [u'room_band_modifiers.id'], ),
        sa.ForeignKeyConstraint(['season_id'], [u'ballot_seasons.year'], ),
        sa.PrimaryKeyConstraint('modifier_id', 'season_id')
    )
    band_prices = op.create_table('room_band_prices',
        sa.Column('band_id', sa.Integer(), nullable=False),
        sa.Column('season_id', sa.Integer(), nullable=False),
        sa.Column('rent', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.ForeignKeyConstraint(['band_id'], [u'room_bands.id'], ),
        sa.ForeignKeyConstraint(['season_id'], [u'ballot_seasons.year'], ),
        sa.PrimaryKeyConstraint('band_id', 'season_id')
    )
    op.create_table('room_listing_modifiers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_listing_id', sa.Integer(), nullable=False),
        sa.Column('band_modifier_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['band_modifier_id'], [u'room_band_modifiers.id'], ),
        sa.ForeignKeyConstraint(['room_listing_id'], [u'room_listings.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('room_listing_id', 'band_modifier_id', name='_listing_modifier_uc')
    )
    op.add_column(u'room_listings', sa.Column('band_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'room_listings', 'room_bands', ['band_id'], ['id'])

    op.bulk_insert(
        bands,
        [
            dict(id=1, name=u"A", description=u"En suite, large"),
            dict(id=2, name=u"B", description=u"En suite, medium"),
            dict(id=3, name=u"C", description=u"En suite, small"),
            dict(id=4, name=u"D", description=u"Set, large+"),
            dict(id=5, name=u"E", description=u"Set, large"),
            dict(id=6, name=u"F", description=u"Set, small"),
            dict(id=7, name=u"G", description=u"Single, large"),
            dict(id=8, name=u"H", description=u"Single, medium"),
            dict(id=9, name=u"I", description=u"Single, small")
        ]
    )

    op.bulk_insert(
        modifiers,
        [
            dict(id=1, name=u"Compensation", description=u"Noise or C+ furniture"),
            dict(id=2, name=u"Bills subsidy", description=u"Deduction to even out bills paid to the morty 3/4 landlady")
        ]
    )

    op.bulk_insert(
        modifier_prices,
        [
            dict(modifier_id=1, season_id=2015, discount=70),
            dict(modifier_id=2, season_id=2015, discount=256.19)
        ]
    )

    op.bulk_insert(
        band_prices,
        [
            dict(band_id=1, season_id=2015, rent=1492.09),
            dict(band_id=2, season_id=2015, rent=1457.10),
            dict(band_id=3, season_id=2015, rent=1379.09),
            dict(band_id=4, season_id=2015, rent=1583.86),
            dict(band_id=5, season_id=2015, rent=1484.20),
            dict(band_id=6, season_id=2015, rent=1418.10),
            dict(band_id=7, season_id=2015, rent=1359.12),
            dict(band_id=8, season_id=2015, rent=1279.42),
            dict(band_id=9, season_id=2015, rent=1166.63)
        ]
    )




    ### end Alembic commands ###


def downgrade_live():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'room_listings', 'band_id')
    op.drop_table('room_listing_modifiers')
    op.drop_table('room_band_prices')
    op.drop_table('room_band_modifier_prices')
    op.drop_table('room_band_modifiers')
    op.drop_table('room_bands')
    ### end Alembic commands ###

